config/routes.rb
Rails.application.routes.draw do
  resources :opos
  resources :users
  resources :unidades
  get 'dashboard/show'

  root to: 'dashboard#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/opo.rb
class Opo < ActiveRecord::Base
  belongs_to :unidade
end

app/models/unidade.rb
class Unidade < ActiveRecord::Base
  has_many :users
  has_many :opos
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  belongs_to :unidade
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authorize

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
  end
end

app/controllers/opos_controller.rb
class OposController < ApplicationController
  before_action :set_opo, only: [:show, :edit, :update, :destroy]

  # GET /opos
  # GET /opos.json
  def index
    if current_user.admin?
      @opos = Opo.all
    else
      @opos = current_user.unidade.oops
    end
  end

  # GET /opos/1
  # GET /opos/1.json
  def show
  end

  # GET /opos/new
  def new
    @opo = Opo.new
  end

  # GET /opos/1/edit
  def edit
  end

  # POST /opos
  # POST /opos.json
  def create
    @opo = Opo.new(opo_params)


    unless current_user.admin?
      @opo.unidade_id = current_user.unidade_id
    end


    respond_to do |format|
      if @opo.save
        format.html { redirect_to @opo, notice: 'Opo was successfully created.' }
        format.json { render :show, status: :created, location: @opo }
      else
        format.html { render :new }
        format.json { render json: @opo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opos/1
  # PATCH/PUT /opos/1.json
  def update
    respond_to do |format|
      if @opo.update(opo_params)
        format.html { redirect_to @opo, notice: 'Opo was successfully updated.' }
        format.json { render :show, status: :ok, location: @opo }
      else
        format.html { render :edit }
        format.json { render json: @opo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opos/1
  # DELETE /opos/1.json
  def destroy
    @opo.destroy
    respond_to do |format|
      format.html { redirect_to opos_url, notice: 'Opo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opo
      @opo = Opo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opo_params
      params.require(:opo).permit(:unidade_id, :numero, :descricao, :data_inicio, :data_fim, :texto)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize # => [:new, :create]
  def create
    user = User.find_by_matricula(params[:matricula])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/unidades_controller.rb
class UnidadesController < ApplicationController
  before_action :set_unidade, only: [:show, :edit, :update, :destroy]

  # GET /unidades
  # GET /unidades.json
  def index
    @unidades = Unidade.all
  end

  # GET /unidades/1
  # GET /unidades/1.json
  def show
  end

  # GET /unidades/new
  def new
    @unidade = Unidade.new
  end

  # GET /unidades/1/edit
  def edit
  end

  # POST /unidades
  # POST /unidades.json
  def create
    @unidade = Unidade.new(unidade_params)

    respond_to do |format|
      if @unidade.save
        format.html { redirect_to @unidade, notice: 'Unidade was successfully created.' }
        format.json { render :show, status: :created, location: @unidade }
      else
        format.html { render :new }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidades/1
  # PATCH/PUT /unidades/1.json
  def update
    respond_to do |format|
      if @unidade.update(unidade_params)
        format.html { redirect_to @unidade, notice: 'Unidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @unidade }
      else
        format.html { render :edit }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidades/1
  # DELETE /unidades/1.json
  def destroy
    @unidade.destroy
    respond_to do |format|
      format.html { redirect_to unidades_url, notice: 'Unidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unidade
      @unidade = Unidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unidade_params
      params.require(:unidade).permit(:nome)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if current_user.admin?
      @users = User.all
    else
      @users = User.where(unidade_id: current_user.unidade_id)
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    # Senha padrao = matricula
    @user.password = @user.matricula
    @user.password_confirmation = @user.matricula

    # Usuario comum so pode criar usuarios em sua propria unidade
    unless current_user.admin?
      @user.unidade_id = current_user.unidade_id
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:matricula, :nome, :unidade_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/opos_helper.rb
module OposHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/show.html.erb
<p><%= link_to "Usuários", users_path %></p>
<% if current_user.admin? -%>
<p><%= link_to "Unidades", unidades_path %></p>
<% end -%>
<p><%= link_to "Ordens", opos_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sistema de Retaguarda</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Início", '/' %> |
<% if current_user %>
  Bem Vindo <b><%= current_user.nome %></b> | <%= link_to "Sair", '/logout' %>
<% else %>
  <%= link_to 'Entrar', '/login' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/opos/_form.html.erb
<%= form_for(@opo) do |f| %>
  <% if @opo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@opo.errors.count, "error") %> prohibited this opo from being saved:</h2>

      <ul>
      <% @opo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.admin? -%>
    <div class="field">
      <%= f.label :unidade_id %><br>
      <%= select("opo", "unidade_id", Unidade.all.collect {|p| [ p.nome, p.id ] }, {include_blank: false}) %>
    </div>    
  <% end -%>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :data_inicio %><br>
    <%= f.date_select :data_inicio %>
  </div>
  <div class="field">
    <%= f.label :data_fim %><br>
    <%= f.date_select :data_fim %>
  </div>
  <div class="field">
    <%= f.label :texto %><br>
    <%= f.text_area :texto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/opos/edit.html.erb
<h1>Editando OPO</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @opo %> |
<%= link_to 'Voltar', opos_path %>

app/views/opos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>OPOs</h1>

<table>
  <thead>
    <tr>
      <th>Número</th>
      <th>Descrição</th>
      <th>Data início</th>
      <th>Data fim</th>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @opos.each do |opo| %>
      <tr>
        <td><%= opo.numero %></td>
        <td><%= opo.descricao %></td>
        <td><%= opo.data_inicio %></td>
        <td><%= opo.data_fim %></td>
        <td><%= opo.texto %></td>
        <td><%= link_to 'Exibir', opo %></td>
        <td><%= link_to 'Editar', edit_opo_path(opo) %></td>
        <td><%= link_to 'Apagar', opo, method: :delete, data: { confirm: 'Tem Certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova OPO', new_opo_path %>

app/views/opos/new.html.erb
<h1>Nova OPO</h1>

<%= render 'form' %>

<%= link_to 'Voltar', opos_path %>

app/views/opos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unidade:</strong>
  <%= @opo.unidade.nome %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @opo.numero %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @opo.descricao %>
</p>

<p>
  <strong>Data inicio:</strong>
  <%= @opo.data_inicio %>
</p>

<p>
  <strong>Data fim:</strong>
  <%= @opo.data_fim %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @opo.texto %>
</p>

<%= link_to 'Editar', edit_opo_path(@opo) %> |
<%= link_to 'Voltar', opos_path %>

app/views/unidades/_form.html.erb
<%= form_for(@unidade) do |f| %>
  <% if @unidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unidade.errors.count, "error") %> prohibited this unidade from being saved:</h2>

      <ul>
      <% @unidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unidades/edit.html.erb
<h1>Editando Unidade</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @unidade %> |
<%= link_to 'Voltar', unidades_path %>

app/views/unidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unidades</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unidades.each do |unidade| %>
      <tr>
        <td><%= unidade.nome %></td>
        <td><%= link_to 'Exibir', unidade %></td>
        <td><%= link_to 'Editar', edit_unidade_path(unidade) %></td>
        <td><%= link_to 'Apagar', unidade, method: :delete, data: { confirm: 'Tem Certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Unidade', new_unidade_path %>

app/views/unidades/new.html.erb
<h1>Nova Unidade</h1>

<%= render 'form' %>

<%= link_to 'Voltar', unidades_path %>

app/views/unidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @unidade.nome %>
</p>

<%= link_to 'Editar', edit_unidade_path(@unidade) %> |
<%= link_to 'Voltar', unidades_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.admin? -%>
    <div class="field">
      <%= f.label :unidade_id %><br>
      <%= select("user", "unidade_id", Unidade.all.collect {|p| [ p.nome, p.id ] }, {include_blank: 'Nenhum'}) %>
    </div>    
  <% end -%>
  
  <div class="field">
    <%= f.label :matricula %><br>
    <%= f.text_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editar Usuário</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @user %> |
<%= link_to 'Voltar', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuários</h1>

<table>
  <thead>
    <tr>
      <th>Matricula</th>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.matricula %></td>
        <td><%= user.nome %></td>
        <td><%= link_to 'Exibir', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Apagar', user, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuário', new_user_path %>

app/views/users/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'form' %>

<%= link_to 'Voltar', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unidae:</strong>
  <%= @user.unidade.nil? ? "Nenhuma" : @user.unidade.nome  %>
</p>


<p>
  <strong>Matricula:</strong>
  <%= @user.matricula %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @user.nome %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Voltar', users_path %>